set -g default-terminal "screen-256color"

# claude 명령어로 창 분할
bind | split-window -h "claude"
bind - split-window -v "claude"

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

set -gq allow-passthrough on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

set -g focus-events on

